name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12']
    name: Node version ${{ matrix.node }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1.4.2

      # Runs a single command using the runners shell
      - name: Yarn Install
        run: yarn

      - name: Yarn Clean
        run: yarn clean

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: |
          yarn build:components
          yarn build:hooks

      - name: Build Store
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SHOP_NAME: ${{ secrets.SHOP_NAME }}
          GRAPHCMS_TOKEN: ${{ secrets.GRAPHCMS_TOKEN }}
          GRAPHCMS_ENDPOINT: ${{ secrets.GRAPHCMS_ENDPOINT }}
        run: |
          yarn store:build
